In [1]:
import numpy as np
import tensorflow as tf

In [4]:
a=np.array([
    [2.1,3.1,3.9],
    [3.2,4.5,3.1]
])

In [6]:
a

array([[2.1, 3.1, 3.9],
       [3.2, 4.5, 3.1]])

In [7]:
a.shape

(2, 3)

In [12]:
np.mean(a,axis=0) #axis=0은 열

array([2.65, 3.8 , 3.5 ])

In [9]:
np.mean(a,axis=1) #axis=1은 행

array([3.03333333, 3.6       ])

tensorflow는 data type에 민감

In [11]:
a+3 #파이썬은 가능(tensorflow는 에러)

array([[5.1, 6.1, 6.9],
       [6.2, 7.5, 6.1]])

===============================================================================================

In [15]:
a=tf.constant(3,dtype=tf.float32) #상수만 저장하는 텐서, a라는 variable 안에 있음
print(a)
#이름 const_1

Tensor("Const_2:0", shape=(), dtype=float32)


In [16]:
a=tf.constant(3,dtype=tf.float32,name='const')
print(a)

Tensor("const_3:0", shape=(), dtype=float32)


In [17]:
a=tf.constant(3,dtype=tf.float32,name='const')
print(a)
#같은 이름을 가진 텐서가 있으면 안되기때문에 컴퓨터가 알아서 1씩 올려줌
#이름 중요

Tensor("const_4:0", shape=(), dtype=float32)


In [19]:
with tf.name_scope('abc'):
    a=tf.constant(3,dtype=tf.float32, name='const')
print(a)
#name_scope안에 텐서 새로 생성

Tensor("abc_1/const:0", shape=(), dtype=float32)


In [20]:
with tf.name_scope('abc'):
    a=tf.constant(3,dtype=tf.float32, name='const')
print(a)

Tensor("abc_2/const:0", shape=(), dtype=float32)


In [ ]:
tf.get_variable('const') #예전에 선언했던 variable 가져옴

In [21]:
with tf.Session() as sess:
    print(sess.run(a))
#위의 셀에서는 그래프를 그리기만 한 것
#이렇게 해야 연산이 된 것임

3.0


In [2]:
a=tf.constant(3,dtype=tf.float32,name='const')
b=tf.Variable(0,dtype=tf.float64)
print(a)
print(b)
#variable(변수) - 값이 바뀔수 있음

Tensor("const:0", shape=(), dtype=float32)
<tf.Variable 'Variable:0' shape=() dtype=float64_ref>


In [ ]:
wiht tf.Session() as sess:
    print(sess.run(a+b))
#이렇게 하면 안됨
#a는 constant, b는 variable
#constant는 값이 바뀌지 않음
#값을 업데이트하고 싶으면 variable을 써야함(나중에 W는 variable로 선언)
#variable은 초기화를 해줘야함

In [13]:
a=tf.constant(3,dtype=tf.float32,name='const')
b=tf.Variable(0,dtype=tf.float32)
c=a+b
print(a)
print(b)

init=tf.global_variables_initializer()

Tensor("const_2:0", shape=(), dtype=float32)
<tf.Variable 'Variable_5:0' shape=() dtype=float32_ref>


In [15]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(c))

3.0


In [17]:
a=tf.constant(3,dtype=tf.float32,name='const')
b=tf.Variable(0,dtype=tf.float32)
c=a+b
print(a)
print(b)

init=tf.global_variables_initializer()

Tensor("const_3:0", shape=(), dtype=float32)
<tf.Variable 'Variable_6:0' shape=() dtype=float32_ref>


In [19]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(b))
    print(sess.run(b))
#이렇게 하면 b에 6이 나올줄 알았는데 안나옴

0.0
0.0


In [20]:
a=tf.constant(3,dtype=tf.float32,name='const')
b=tf.Variable(0,dtype=tf.float32)
c=tf.assign(b,a+b)
print(a)
print(b)

init=tf.global_variables_initializer()

Tensor("const_4:0", shape=(), dtype=float32)
<tf.Variable 'Variable_7:0' shape=() dtype=float32_ref>


In [16]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(b))
    print(sess.run(b))

0.0
0.0


## placeholder

placeholder: 그래프로 tensor를 입력하는 객체, 초기값을 제공하지 않아도 되므로 런타임에 지정 가능<br>
variable: 선언할때 초기값을 제공

In [7]:
x=tf.placeholder(tf.float32, shape=(),name='x')
y=tf.placeholder(tf.float32, shape=(),name='y')
w=tf.Variable(np.random.randn(),dtype=tf.float32)

a= tf.assign(w,w+x+y)

init=tf.global_variables_initializer()

In [8]:
with tf.Session() as sess:
    sess.run(init)    
    for _ in range(0,10):
        print(sess.run(w))
        sess.run(a,feed_dict={x:1.0,y:2.0})
    print(sess.run(w))

-1.5189161
1.4810839
4.481084
7.481084
10.481084
13.481084
16.481083
19.481083
22.481083
25.481083
28.481083


In [9]:
np.random.seed(42)
x=tf.placeholder(tf.float32, shape=(),name='x')
y=tf.placeholder(tf.float32, shape=(),name='y')
w=tf.Variable(np.random.randn(),dtype=tf.float32)
a= tf.assign(w,w+x+y)
init=tf.global_variables_initializer()

In [10]:
with tf.Session() as sess:
    sess.run(init)    
    for _ in range(0,10):
        print(sess.run(w))
        sess.run(a,feed_dict={x:1.0,y:2.0})
    print(sess.run(w))

0.49671414
3.496714
6.496714
9.496714
12.496714
15.496714
18.496714
21.496714
24.496714
27.496714
30.496714
